### ISSUE TITLE
Display Errors

### ISSUE THREAD

**Issue by anthonyjclarke** [vilaca/Handheld-Color-Console#1]
Hi, wondering if you have any idea why this is...?

Using a 240x320 2.4 TFT SPI (http://www.ebay.com.au/itm/2-4-240x320-SPI-TFT-LCD-Touch-Panel-Serial-Port-Module-with-PBC-ILI9341-5V-3-3V-/400759772993?pt=LH_DefaultDomain_15&hash=item5d4f24d741)

Display is inverted and cropped.  Double checked my connections 20 times :)
![20150613_222356896_ios](https://cloud.githubusercontent.com/assets/9491428/8146207/1c073e08-1270-11e5-9310-a7788467cf50.jpg)

**Comment by vilaca** [comment]
I don't have that screen so I can't test, but AFAICT is the same controller so _should_ work fine.

Can you test different values in line [162 of TFTv2_extended.cpp](https://github.com/vilaca/Handheld-Color-Console/blob/master/ArduinoTetris/TFTv2_extended.cpp#L162) ?

Current value is 0xE8. Can you test 0xC8, 0x48, 0x68 and 0x28 ?

**Comment by anthonyjclarke** [comment]
Thanks. Will do and let you know. 
Btw can you send me exact details of your TFT??

**Comment by anthonyjclarke** [comment]
Tried all values, no change always displays the same... can you send me link / details on the screen you are using?

**Comment by vilaca** [comment]
I'm sorry it didn't work.

This is the one I'm using. It's 2.2 inches, ILI9341 controller and no touch interface: http://www.ebay.co.uk/itm/161648895078?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT

**Comment by vilaca** [comment]
Closing. Works fine with supported screens.
